# .github/release.yml

changelog:
  categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📝 Documentation'
    labels:
      - 'documentation'
      - 'docs'
      - 'readme'
  - title: 🃏 Miscellaneous
    labels:
      - "*"